### ISSUE TITLE
Multiple values choice set linked to a category

### ISSUE THREAD

**Issue by lucaguindani** [catima/catima#322]
When a category is linked to a choice in a multiple values choice set, sometimes the category will show up sometimes not. In the example below the category is linked to the "Alpes bernoises" choice.

![category_multiple_values](https://user-images.githubusercontent.com/1675064/112487653-2ff5d300-8d7d-11eb-8761-09ba99528b0d.gif)

**Comment by abstracts33d** [comment]
this issue preexist this feature 

(all screenshots made from develop without the feature merged)

exactly the same conditions that [https://github.com/catima/catima/issues/321](https://github.com/catima/catima/issues/321)

![image](https://user-images.githubusercontent.com/16547134/112651715-f2607b00-8e4c-11eb-871b-12efda320f24.png)
...
![image](https://user-images.githubusercontent.com/16547134/112651780-03a98780-8e4d-11eb-93db-653f18fb6b69.png)

this need further investigations as to why it is not functionning properly.
it may be fixed by the redesign of the toogling logic for [https://github.com/catima/catima/issues/321](https://github.com/catima/catima/issues/321)
