### ISSUE TITLE
[Data Edition] Data from "Reference field" not displayed after edition

### ISSUE THREAD

**Issue by mmercapi** [catima/catima#85]
Editing data can cause data display problem, if forementioned data is from a reference field.

Example below shows edition of a "Bibliothèque". 

After saving changes, if the field "Université" has not been changed (normal case), it's data are not displayed either in DATA mode or in SITE mode, even though edited fields are taken into account.  

Current solution consists in changing, the value to a temporary one and coming back to the previous (aka initial desired) value.

![image](https://user-images.githubusercontent.com/26297183/46666925-58e37700-cbc8-11e8-9887-65d6475e5473.png)

![image](https://user-images.githubusercontent.com/26297183/46667067-b5df2d00-cbc8-11e8-8d09-553a7fc3a12d.png)

**Comment by lucaguindani** [comment]
I have something that could be related with a multiple value reference field

![reference-multiple](https://user-images.githubusercontent.com/1675064/46796846-ddabcd80-cd4d-11e8-9bb6-9101de7ff139.png)

**Comment by lucaguindani** [comment]
It's maybe related to the formatted text issue fixed here https://github.com/catima/catima/pull/83/files.
And maybe also to the data loss of the specific issue.

**Comment by lucaguindani** [comment]
Now I think the first issue

https://github.com/catima/catima/issues/85#issuecomment-428886029

And the second

https://github.com/catima/catima/issues/85#issuecomment-428897909

are separated issues

**Comment by jurtn** [comment]
These are two separate issues. I suggest opening a second issue for the formatted text display issue.

The raw value problem comes from the JSON attribute data store backend. The integer value for the reference is transformed into a hash here: https://github.com/catima/catima/blob/95bac25da7082d43b4486236970cded839865df6/app/models/data_store/json_attribute.rb#L90

I am not completely sure why this has been done this way. From [a comment in the DateTimePresenter](https://github.com/catima/catima/blob/95bac25da7082d43b4486236970cded839865df6/app/presenters/field/date_time_presenter.rb#L14) I assume this must be an old representation and should basically be removed.

There is a [test associated with this behaviour](https://github.com/catima/catima/blob/95bac25da7082d43b4486236970cded839865df6/test/models/data_store/json_attribute_test.rb#L18), but otherwise there seems to be no impact on the application by removing this behavior.
